<script lang="ts">
  // Film pour le futur site de présentation, servi par une entrée indépendante.
  // Palette Titane, une idée par plan.
  // Hiérarchie : titre 72 px, interface réelle, annotations 20 px ; grille 8 px.
  import { onMount, tick } from 'svelte';
  import Chart from './Chart.svelte';
  import Brand from '../src/lib/components/Brand.svelte';
  import Icon from '../src/lib/components/Icon.svelte';
  import darkImage from './film-assets/overview-dark.png';
  import lightImage from './film-assets/overview-light.png';
  const capture = new URLSearchParams(location.search).get('capture') === '1';
  const duration = 42.5;
  let time = $state(0), playing = $state(false), scale = $state(1);
  const clamp=(v:number)=>Math.max(0,Math.min(1,v));
  const ease=(v:number)=>1-Math.pow(1-clamp(v),3);
  const enter=(start:number,length=.8)=>ease((time-start)/length);
  const opacity=(start:number,end:number)=>enter(start,.65)*ease((end-time)/.45);
  const scene=(start:number,end:number)=>`opacity:${opacity(start,end)};visibility:${time>=start&&time<=end?'visible':'hidden'};transform:translateY(${(1-enter(start))*20}px)`;
  const lines=['<script lang="ts">',"  import Chart from './Chart.svelte';","  import ThemePicker from './ThemePicker.svelte';",'',"  let range = $state('24h');",'</'+'script>','', '<ThemePicker ontheme={themeChange} />','{#key range}','  <Chart {range} />','{/key}'];
  const chapters=['Une vision claire','Tout converge','Explorer les données','Passer à l’action','À toute heure','Dans les coulisses','CairnOps'];
  const chapter=$derived(time<4.5?0:time<10.5?1:time<17?2:time<23.5?3:time<29.5?4:time<37.5?5:6);
  const ack=$derived(time>=21.2);
  function replay(){time=0;playing=true;}
  onMount(()=>{
    document.documentElement.dataset.theme='dark';
    const resize=()=>scale=Math.min(innerWidth/1920,innerHeight/1080);
    resize();window.addEventListener('resize',resize);
    let previous=performance.now(),frame=0;
    const loop=(stamp:number)=>{const delta=(stamp-previous)/1000;previous=stamp;if(playing){time=Math.min(duration,time+delta);if(time===duration)playing=false;}frame=requestAnimationFrame(loop);};
    if(!capture){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;playing=!reduced;if(reduced)time=2.8;frame=requestAnimationFrame(loop);}
    (window as unknown as {__setFilmTime:(value:number)=>Promise<void>}).__setFilmTime=async(value)=>{playing=false;time=clamp(value/duration)*duration;await tick();};
    return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize);};
  });
</script>

{#snippet logo(size=64)}
  <Brand width={size} symbolOnly/>
{/snippet}
{#snippet heading(kicker:string,title:string,subtitle:string)}<header class="m-heading"><span class="m-kicker">{kicker}</span><h2>{title}</h2><p>{subtitle}</p></header>{/snippet}
{#snippet chrome(label:string)}<div class="m-chrome"><i></i><i></i><i></i><span>CairnOps / {label}</span></div>{/snippet}

<main class="m-shell" aria-label="Film CairnOps : présentation et coulisses du développement">
  <div class="m-canvas" style={`transform:translate(-50%,-50%) scale(${scale})`}>
    <div class="m-background"></div><div class="m-brand"><Brand width={154}/></div><div class="m-edition">PRODUIT & DÉVELOPPEMENT <span>01</span></div>
    <section class="m-scene m-intro" style={scene(0,5)} aria-label="Introduction"><div class="m-symbol" style={`opacity:${enter(.2)};transform:translateY(${(1-enter(.2))*25}px)`}>{@render logo(84)}</div><h1 style={`opacity:${enter(.5)};transform:translateY(${(1-enter(.5))*35}px)`}>Votre infrastructure.<br/><span>Une vision claire.</span></h1><p style={`opacity:${enter(1.25)}`}>La supervision, pensée dans les détails.</p><div class="m-intro-line" style={`transform:scaleX(${enter(1.5,1.5)})`}></div></section>
    <section class="m-scene" style={scene(4.5,11)} aria-label="Vue d’ensemble"><div class="m-overview-copy"><span class="m-kicker">01 / L’ESSENTIEL</span><h2>Tout<br/>converge.</h2><p>Cibles, sources, incidents.<br/>Un seul état partagé.</p><div class="m-summary" style={`opacity:${enter(6.5)}`}><i></i><div><strong>48 cibles</strong><span>Une lecture commune</span></div></div></div><div class="m-browser m-overview-screen" style={`transform:translate(${(1-enter(4.8,1.1))*100}px,${(1-enter(4.8,1.1))*40}px) scale(${.97+enter(4.8,6)*.04});opacity:${enter(4.8)}`}>{@render chrome('Vue d’ensemble')}<img src={darkImage} alt="Vue d’ensemble du prototype CairnOps en sombre"/></div></section>
    <section class="m-scene" style={scene(10.5,17.5)} aria-label="Graphiques interactifs">{@render heading('02 / COMPRENDRE','Les chiffres prennent du sens.','Explorer une tendance. Revenir à la preuve.')}<div class="m-chart-card" style={`opacity:${enter(10.9)};transform:translateY(${(1-enter(10.9))*40}px)`}><div class="m-chart-top"><div><span>API publique</span><strong>184 <small>ms</small></strong></div><div class="m-chart-source"><Icon name="signal" size={21}/>Uptime Kuma<span>24 heures</span></div></div><Chart interactive={false} reveal={enter(11.3,2.8)} label="Temps de réponse du scénario de démonstration"/><div class="m-chart-bottom"><span><i></i>Indicateur contextuel</span><span>Le signal reste relié à sa source.</span></div></div><div class="m-data-note" style={`opacity:${enter(13.5)}`}><span>99,94 <small>%</small><em>Disponibilité</em></span><span>100 <small>%</small><em>Couverture</em></span><p>Un pourcentage.<br/>Le contexte pour lui faire confiance.</p></div></section>
    <section class="m-scene" style={scene(17,24)} aria-label="Prise en charge d’un incident"><div class="m-action-copy"><span class="m-kicker">03 / AGIR</span><h2>Comprendre.<br/>Puis agir.</h2><p>La preuve, son origine,<br/>la décision de l’opérateur.</p><span class="m-action-caption" style={`opacity:${enter(21.4)}`}>Pris en charge.<br/>La supervision continue.</span></div><div class="m-evidence" style={`opacity:${enter(17.3)};transform:translateX(${(1-enter(17.3))*65}px)`}><div class="m-evidence-header"><span class="m-warn"><i></i>Avertissement</span><span>Incident / API publique</span></div><h3>Temps de réponse élevé</h3><p>Depuis 14:18 · Assurance signalée</p><div class="m-proof"><div><span class="m-source">U</span><strong>Uptime Kuma</strong><span>Preuve active</span></div><p>184 ms observées.<br/>Seuil de 150 ms défini dans Uptime Kuma.</p></div><div class="m-timeline"><i></i><span>14:18</span><strong>Incident ouvert</strong></div><div class="m-timeline" style={`opacity:${enter(21.2)};transform:translateY(${(1-enter(21.2))*14}px)`}><i></i><span>14:32</span><strong>Pris en charge par Grégory</strong></div><div class="m-ack-button" class:done={ack} style={`transform:scale(${time>20.85&&time<21.2?.98:1})`}>{ack?'✓  Incident acquitté':'Acquitter l’incident'}</div><div class="m-pointer" style={`opacity:${opacity(19.5,21.5)};transform:translate(${(1-enter(19.6,1.3))*200}px,${(1-enter(19.6,1.3))*110}px)`}><svg width="34" height="40" viewBox="0 0 34 40" aria-hidden="true"><path d="M3 2v29l8-8 7 14 6-3-7-13h12Z" fill="white" stroke="var(--bg)" stroke-width="2"/></svg></div></div></section>
    <section class="m-scene" style={scene(23.5,30)} aria-label="Thèmes clair et sombre">{@render heading('04 / S’ADAPTER','La clarté, à toute heure.','Clair. Sombre. Système. Solaire.')}<div class="m-browser m-theme-screen" style={`opacity:${enter(23.8)};transform:translateY(${(1-enter(23.8))*28}px)`}>{@render chrome('Apparence')}<div class="m-theme-images"><img src={darkImage} alt="Interface sombre"/><div class="m-light-reveal" style={`clip-path:inset(0 ${100-enter(24.7,3)*100}% 0 0)`}><img src={lightImage} alt="La même interface en clair"/></div><div class="m-divider" style={`left:${enter(24.7,3)*100}%;opacity:${time>24.7&&time<27.7?1:0}`}></div></div></div><div class="m-modes"><span><Icon name="sun" size={20}/>Clair</span><span><Icon name="moon" size={20}/>Sombre</span><span><Icon name="settings" size={20}/>Système</span><span class="m-solar"><Icon name="sun" size={20}/>Solaire<small>Au rythme du soleil</small></span></div></section>
    <section class="m-scene" style={scene(29.5,38)} aria-label="Coulisses du développement">{@render heading('05 / DANS LES COULISSES','Le soin se construit.','Des composants simples. Des détails vérifiés.')}<div class="m-code-window" style={`opacity:${enter(29.9)};transform:translateY(${(1-enter(29.9))*24}px)`}><header><span class="m-code-file">App.svelte</span><span>Svelte 5 · TypeScript</span></header><div class="m-code-lines">{#each lines as line,i}<div style={`opacity:${enter(30.3+i*.13,.4)};transform:translateY(${(1-enter(30.3+i*.13,.4))*8}px)`}><span>{String(i+1).padStart(2,'0')}</span><code class:import-line={i===1||i===2} class:state-line={i===4}>{line||' '}</code></div>{/each}</div></div><div class="m-checks">{#each [{title:'Une grammaire commune',text:'Icônes, alignements, composants.',icon:'overview' as const},{title:'Des thèmes éprouvés',text:'Système, soleil, jours et nuits polaires.',icon:'sun' as const},{title:'Une interface vérifiée',text:'Clavier et écrans de 320 à 1 440 px.',icon:'health' as const}] as item,i}<div style={`opacity:${enter(31+i*1.4)};transform:translateX(${(1-enter(31+i*1.4))*24}px)`}><span><Icon name={item.icon} size={25}/></span><div><strong>{item.title}</strong><p>{item.text}</p></div><b>✓</b></div>{/each}<p class="m-svelte" style={`opacity:${enter(35.5)}`}>Conçu en Svelte.<br/><strong>Façonné pour CairnOps.</strong></p></div></section>
    <section class="m-scene m-outro" style={scene(37.5,43.5)} aria-label="Conclusion"><div style={`opacity:${enter(37.9)};transform:translateY(${(1-enter(37.9))*24}px)`}><Brand width={560}/><h2 class="p-sr">CairnOps</h2></div><p style={`opacity:${enter(38.6)}`}>La supervision, en toute clarté.</p><span style={`opacity:${enter(39.4)}`}>Direction d’interface · Septembre 2026</span></section>
    <footer class="m-footer"><span>PROTOTYPE · DONNÉES DE DÉMONSTRATION</span><span>{String(chapter+1).padStart(2,'0')} / {chapters[chapter]}</span></footer>
  </div>
  {#if !capture}<div class="m-controls"><button onclick={()=>{if(time>=duration)replay();else playing=!playing;}}>{playing?'Pause':'Lire'}</button><button onclick={replay}>Rejouer</button><input aria-label="Position dans le film" type="range" min="0" max={duration} step=".1" bind:value={time}/><span>{Math.floor(time)} / 42 s</span></div>{/if}
</main>

<style>
  .m-shell{position:fixed;inset:0;background:var(--bg);overflow:hidden;color:var(--ink);font-family:var(--font)}.m-canvas{position:absolute;left:50%;top:50%;width:1920px;height:1080px;overflow:hidden;background:var(--bg);--p-surface:var(--surface);--p-surface-raised:var(--surface-2);--p-line:var(--line);--p-line-strong:var(--line-strong);--p-faint:var(--faint);--p-chart-color:var(--chart-context);--p-ink:var(--ink)}.m-background{position:absolute;inset:0;background:radial-gradient(ellipse at 65% 35%,var(--surface) 0,transparent 65%)}
  .m-brand{position:absolute;top:48px;left:80px;display:flex;align-items:center;gap:10px;font-size:20px;font-weight:600;letter-spacing:-.5px;z-index:10}.m-edition{position:absolute;top:58px;right:80px;font-size:11px;letter-spacing:1.6px;color:var(--faint);z-index:10}.m-edition>span{border:1px solid var(--line);border-radius:4px;padding:5px 7px;margin-left:18px;letter-spacing:0}
  .m-scene{position:absolute;inset:0;will-change:opacity,transform}.m-scene h1,.m-scene h2,.m-scene h3,.m-scene p{margin:0}.m-scene h2{font-size:64px;line-height:1.08;letter-spacing:-2.7px;font-weight:550}.m-scene p{font-size:24px;line-height:1.55;color:var(--muted);letter-spacing:-.3px}.m-kicker{display:block;color:var(--accent);font-size:12px;letter-spacing:2px;margin-bottom:28px}.m-intro{display:flex;flex-direction:column;align-items:center;justify-content:center;padding-bottom:24px}.m-symbol{color:var(--accent);margin-bottom:34px}.m-intro h1{text-align:center;font-size:82px;font-weight:550;line-height:1.11;letter-spacing:-4px}.m-intro h1>span{color:var(--muted)}.m-intro p{margin-top:28px;font-size:25px}.m-intro-line{width:60px;height:3px;margin-top:46px;background:var(--accent)}
  .m-overview-copy{position:absolute;left:140px;top:270px;width:430px}.m-overview-copy h2{font-size:90px;line-height:1.02;letter-spacing:-4px}.m-overview-copy p{margin-top:30px;font-size:25px}.m-summary{display:flex;align-items:center;gap:16px;border-top:1px solid var(--line);margin-top:66px;padding-top:28px;width:285px}.m-summary>i{width:7px;height:7px;border-radius:50%;background:var(--accent)}.m-summary strong{display:block;font-size:23px;font-weight:500}.m-summary div>span{display:block;font-size:15px;color:var(--faint);margin-top:5px}.m-browser{overflow:hidden;border-radius:12px;border:1px solid var(--line-strong);box-shadow:0 35px 110px rgba(0,0,0,.3)}.m-chrome{height:38px;background:var(--surface-2);display:flex;align-items:center;gap:6px;padding:0 15px;border-bottom:1px solid var(--line-strong)}.m-chrome>i{width:6px;height:6px;border-radius:50%;background:var(--dim)}.m-chrome>span{margin-left:14px;color:var(--faint);font-size:10px}.m-overview-screen{position:absolute;left:625px;top:188px;width:1360px;height:780px;transform-origin:center}.m-overview-screen img{display:block;width:100%;height:auto}
  .m-heading{position:absolute;top:162px;left:0;right:0;text-align:center}.m-heading .m-kicker{margin-bottom:20px}.m-heading h2{font-size:64px}.m-heading p{font-size:23px;margin-top:18px}.m-chart-card{position:absolute;left:245px;top:358px;width:1430px;padding:32px 36px 24px;border:1px solid var(--line-strong);background:var(--surface);border-radius:12px}.m-chart-top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px}.m-chart-top>div>span{font-size:16px;color:var(--muted)}.m-chart-top strong{display:block;font-size:44px;line-height:1.1;margin-top:12px;font-weight:550;letter-spacing:-1.5px}.m-chart-top strong small{font-size:20px;color:var(--faint);letter-spacing:0;font-weight:400}.m-chart-source{display:flex;align-items:center;gap:10px;font-size:15px;color:var(--muted)}.m-chart-source>span{font-size:13px!important;border:1px solid var(--line-strong);border-radius:5px;padding:7px 11px;margin-left:10px}.m-chart-bottom{display:flex;justify-content:space-between;border-top:1px solid var(--line);padding-top:20px;font-size:14px;color:var(--faint);margin-top:10px}.m-chart-bottom>span:first-child{display:flex;align-items:center;gap:8px}.m-chart-bottom i{width:18px;height:2px;background:var(--chart-context)}.m-data-note{position:absolute;left:390px;right:390px;top:945px;display:flex;align-items:center;gap:70px}.m-data-note>span{font-size:30px;font-weight:500;letter-spacing:-.8px}.m-data-note small{font-size:16px;color:var(--faint)}.m-data-note em{display:block;font-size:13px;font-style:normal;font-weight:400;color:var(--faint);margin-top:5px;letter-spacing:0}.m-data-note p{font-size:17px;margin-left:auto;line-height:1.5}
  .m-action-copy{position:absolute;left:165px;top:270px}.m-action-copy h2{font-size:76px;letter-spacing:-3.4px;line-height:1.07}.m-action-copy p{margin-top:30px;font-size:25px}.m-action-caption{display:block;font-size:20px;line-height:1.55;color:var(--muted);margin-top:60px;border-left:2px solid var(--accent);padding-left:20px}.m-evidence{position:absolute;right:175px;top:196px;width:840px;padding:42px 44px 38px;border-radius:12px;border:1px solid var(--line-strong);background:var(--surface);box-shadow:0 30px 100px rgba(0,0,0,.2)}.m-evidence-header{display:flex;align-items:center;justify-content:space-between;font-size:13px;color:var(--faint)}.m-warn{display:flex;align-items:center;gap:6px;border:1px solid var(--warn-line);border-radius:5px;color:var(--warn);padding:6px 9px;font-size:12px}.m-warn i{height:4px;width:4px;border-radius:50%;background:var(--warn)}.m-evidence h3{font-size:36px;letter-spacing:-1.1px;font-weight:550;margin-top:30px}.m-evidence>p{font-size:17px;margin-top:13px}.m-proof{background:var(--bg);border:1px solid var(--line);border-radius:8px;margin-top:32px;padding:24px}.m-proof>div{display:flex;align-items:center;gap:12px;font-size:17px}.m-proof strong{font-weight:500}.m-source{display:grid;place-items:center;width:28px;height:28px;border:1px solid var(--line-strong);border-radius:5px;font-size:12px;color:var(--muted)}.m-proof>div>span:last-child{font-size:12px;color:var(--warn);margin-left:auto}.m-proof p{font-size:19px;margin-top:20px;line-height:1.6}.m-timeline{display:flex;align-items:center;gap:16px;padding:24px 0 0;font-size:16px}.m-timeline>span{font-size:13px;color:var(--faint)}.m-timeline strong{font-weight:450}.m-timeline i{height:6px;width:6px;border:1px solid var(--warn);border-radius:50%;margin-left:2px}.m-ack-button{margin-top:32px;width:100%;padding:18px;text-align:center;border-radius:6px;background:var(--accent);color:var(--accent-ink);font-size:18px;font-weight:550}.m-ack-button.done{background:var(--surface-2);color:var(--ink);border:1px solid var(--line-strong);padding:17px}.m-pointer{position:absolute;bottom:50px;right:232px}
  .m-theme-screen{position:absolute;left:240px;top:350px;width:1440px;height:567px}.m-theme-images{position:relative;width:100%;height:100%;overflow:hidden}.m-theme-images img{display:block;width:100%;height:auto}.m-light-reveal{position:absolute;inset:0}.m-divider{position:absolute;top:0;bottom:0;width:2px;background:var(--accent)}.m-modes{position:absolute;top:950px;left:240px;right:240px;display:flex;align-items:center;justify-content:center;gap:52px;color:var(--muted);font-size:18px}.m-modes>span{display:flex;align-items:center;gap:10px}.m-modes .m-solar{color:var(--accent)}.m-solar small{font-size:12px;color:var(--faint);margin-left:8px}
  .m-code-window{position:absolute;left:175px;top:365px;width:975px;height:530px;background:var(--surface);border:1px solid var(--line-strong);border-radius:10px;overflow:hidden}.m-code-window>header{height:52px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);font-size:13px;color:var(--faint);padding-right:24px}.m-code-file{display:flex;align-items:center;height:100%;padding:0 24px;border-right:1px solid var(--line);border-top:2px solid var(--accent);color:var(--ink);background:var(--surface-2)}.m-code-lines{padding:29px 0}.m-code-lines>div{display:flex;align-items:center;min-height:34px;font-size:20px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.m-code-lines>div>span{width:70px;text-align:center;font-size:13px;color:var(--faint)}.m-code-lines code{color:var(--chart-context);white-space:pre}.m-code-lines code.import-line{color:var(--muted)}.m-code-lines code.state-line{color:var(--accent)}.m-checks{position:absolute;left:1220px;right:135px;top:382px}.m-checks>div{display:flex;align-items:center;gap:20px;padding:27px 0;border-bottom:1px solid var(--line)}.m-checks>div>span{color:var(--muted)}.m-checks strong{font-size:20px;font-weight:500;letter-spacing:-.3px}.m-checks p{font-size:14px;line-height:1.55;color:var(--faint);margin-top:9px;letter-spacing:0}.m-checks b{margin-left:auto;font-size:17px;color:var(--ok);font-weight:400}.m-checks .m-svelte{font-size:23px;color:var(--faint);line-height:1.6;margin-top:44px}.m-svelte strong{font-size:23px;color:var(--ink);font-weight:500}
  .m-outro{display:flex;align-items:center;justify-content:center;flex-direction:column}.m-outro>div{display:flex;align-items:center;gap:22px;color:var(--accent)}.m-outro h2{font-size:100px;font-weight:600;letter-spacing:-4.5px;color:var(--ink)}.m-outro>p{font-size:30px;margin-top:30px;letter-spacing:-.5px}.m-outro>span{font-size:14px;color:var(--faint);margin-top:70px}.m-footer{position:absolute;left:80px;right:80px;bottom:35px;display:flex;justify-content:space-between;color:var(--faint);font-size:10px;letter-spacing:.8px;z-index:10}.m-footer>span:last-child{color:var(--faint);letter-spacing:.3px}
  .m-controls{position:absolute;bottom:16px;left:50%;transform:translateX(-50%);display:flex;align-items:center;gap:12px;padding:9px 14px;background:var(--surface-2);border:1px solid var(--line-strong);border-radius:8px;color:var(--ink);font-size:11px;z-index:20;max-width:calc(100vw - 16px)}.m-controls>button{background:var(--surface-3);border:1px solid var(--line-strong);color:var(--ink);border-radius:4px;padding:6px 10px;cursor:pointer;font:inherit}.m-controls input{width:160px;accent-color:var(--accent)}.m-controls>span{white-space:nowrap;font-variant-numeric:tabular-nums}.m-controls :focus-visible{outline:2px solid var(--accent);outline-offset:3px}@media(max-width:600px){.m-controls{gap:7px;padding:7px}.m-controls>span{display:none}.m-controls input{width:90px}}
  .m-chart-card :global(.p-chart){max-width:1240px;margin:0 auto}
</style>
